::ping -n 60 127.0.0.1 >nul
db2 -tvf "00a.bufferpool activity.sql"
db2 -tvf "01.The number of transactions, SELECT statements, and INSERT, UPDATE, or DELETE statements executed.sql"
db2 -tvf "01a.The number of transactions, SELECT statements, and INSERT, UPDATE, or DELETE statements executed.sql"
db2 -tvf "02.Buffer pool hit ratios, measured separately for data and index activity.sql"
db2 -tvf "03.Buffer pool physical reads and writes per transaction.sql"
db2 -tvf "04.The ratio of database rows read to rows returned.sql"
db2 -tvf "05.The amount of time spent sorting per transaction adb totals.sql"
db2 -tvf "06.The amount of lock wait time accumulated per thousand transactions.sql"
db2 -tvf "07.The number of deadlocks and lock timeouts per thousand transactions.sql"
db2 -tvf "08.The number of dirty steal triggers per thousand transactions.sql"
db2 -tvf "09.The number of package cache inserts per thousand transactions, and the percent of time spent compiling SQL.sql"
db2 -tvf "10.The amount of log activity per transaction, and the time per log write.sql"
db2 -tvf "10a.The amount of log activity per transaction, and the time per log write.sql"
db2 -tvf "11.In partitioned database environments, the number of fast communication manager (FCM) buffers sent and received between partitions.sql"
db2 -tvf "12.Average time in milliseconds for buffer pool reads and writes, and for direct read and write requests.sql"
